name: First Actions Sample
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - name: Build core
        run: yarn build
        working-directory: ./packages/core
      - name: Build web
        run: yarn build
        working-directory: ./packages/web-webpack
      - name: Archive web
        uses: actions/upload-artifact@v2
        with:
          name: web-output
          path: packages/web-webpack/out
